name: Build & Release

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: 'release-key.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build the app
        run: ./gradlew assembleRelease\
                -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }}\
                -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }}\
                -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }}\
                -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
